### PR TITLE
Add my info Kirsty :)

### PR DESCRIPTION
**Pull request by KirstyElliphant**
Hi Kat!

I added my info....

### CODE REVIEW

**Comment by KirstyElliphant** [comment]
Adding info for Kirsty Elliott

**Comment by RonaCostello** [comment]
Wicked! ;)

**Review by lizzieab — COMMENTED** [review]
Looking good, but fail on being late ;)

**Comment by RonaCostello** [comment]
M8 you need to add some more info too 😘

**Comment by SandrineP** [comment]
Following you! ;-)

**Pull request merged**
